### ISSUE TITLE
Merge changes from the singnet fork

### ISSUE THREAD

**Issue by ntoxeg** [opencog/spacetime#6]
I am opening this as a reminder for @ngeiswei or someone else to merge changes from the singnet fork - without them there is no `PredictiveImplicationScope` defined.

**Comment by linas** [comment]
The correct way to do changes is to create pull requests. 

Spacetime has nothing to do with predicative implication, so this is the wrong repo.

Please note: the intended usage is that the singnet fork is a dumping ground for random stuff; anything goes, it doesn't get any testing, quality control or review. The goal is to allow fast and easy experiments. The stuff that works, that is well-designed and debuged, it gets merged into opencog repos.  Thus, the singnet branches will typically have more stuff, but it will be of lower quality.

**Comment by ntoxeg** [comment]
> Spacetime has nothing to do with predicative implication, so this is the wrong repo.

It does, the current spacetime repository defines `PredictiveImplication`, the singnet fork additionally has `PredictiveImplicationScope`. This **is** the right repo - and you can’t build ROCCA without relying on the singnet fork already.

That said, if the singnet implementation is still considered experimental (even though it’s been months and it’s used by other projects) and unfit for merging into here, so be it.

**Comment by linas** [comment]
1) The correct procedure is to open a pull request

2) spacetime is unmaintained. No one maintains it.  Best of my knowledge, it is not used anywhere by anyone.

3) I cannot even begin to imagine what predicative implication has to do with spacetime; this sounds like a bug to me, and/or a classic example of shitty code. The spacetime module is meant to be for working with space and time, and not for reasoning.  Whoever jammed that in there simply put it in the wrong place.

4) I don't know what ROCCA is. I imagine you should talk to the maintainer for ROCCA to see what to do?

**Comment by ntoxeg** [comment]
Ad 1. I am not arguing with that point, sorry for bringing this up this way but I wanted to send this through an official channel.

Ad 2. Except it is used - unfortunately the way it has been done seems to somehow fall through the gaps of this organisation’s management process…

Ad 3. “predictive” (not “predicative"), because it deals with predictions - statements relating knowledge attached to different points in *time*. Anyway, it is certainly arguable why that code has been put here and not in the PLN repository - but there is literally a comment in the temporal reasoning directory there directing you **here**.

Ad 4. Yeah, but this is supposed to be OpenCog-side functionality, and it is already present (whether rightfully so or not) in spacetime.

Overall, whatever - I can obviously live with pulling the code from the singnet spacetime, although it seems silly that this is how it has to be.

I guess I should open an issue for PLN to bring this whole temporal logic code there? Maybe I’ll sort this out and make a PR, if I find time.

Anyway, I apologise for bothering you with this but I kind of want this mess to be sorted out.

**Comment by linas** [comment]
You're not bothering me; I'm just saying that this is the wrong forum.

I don't know who created these things, or why they are being created, or who is doing what.  I cannot be everyone's janitor, cleaning up messes created by randos who cannot be bothered to, as you say, to use "official channels" to communicate with the "organization's management".  The only other "organization" involved here is singularity.net, and they have paid staff who are supposed to know how to manage github repos, issues and pull reqs.  If their staff is allowing people to make a mess, that's their problem. I won't be the one cleaning out the toilet.  Especially, when it's someone-else's toilet.

**Comment by vsbogd** [comment]
@ntoxeg , `opencog` is being merged to `singnet` regularly. As far as  I can say there are no changes in `opencog/spacetime` which are not in `singnet/spacetime`. So you can use `singnet` fork instead of `opencog`.

**Comment by ntoxeg** [comment]
@vsbogd this is not important anymore, it seems there are changes from `spacetime` that should be ported to PLN and as it turns out they are really simple. Also my point was to not have to split attention between `opencog` and `singnet` - there is an `opencog` project already using this so the functionality should be present in “`opencog`-land”.

**Comment by linas** [comment]
@vsbogd - you should not encourage anyone to use the singnet code-base.  The deal was that signnet would contain all the ugly, buggy, crashy and unstable code; when it was finished and design-complete, it would get merged into the opencog repos. Pointing users at bleeding-edge code is generically a bad idea.
